{"uuid": "acb75855-e322-4076-a9f6-104fd314d645", "children": ["2dfe55c3-ffd0-4415-9217-8d20349551b1"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "webium.errors.WebiumException: Can't open page without url\n", "trace": "  File \"C:\\Users\\79605\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\79605\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\79605\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"C:\\Development\\autotests\\conftest.py\", line 19, in driver\n    url=''\n  File \"C:\\Development\\autotests\\base\\ui\\login_page\\page_login.py\", line 8, in __init__\n    self.open()\n  File \"C:\\Development\\autotests\\venv\\lib\\site-packages\\webium\\base_page.py\", line 62, in open\n    raise WebiumException('Can\\'t open page without url')\n"}, "start": 1608992175919, "stop": 1608992178869}], "start": 1608992175919, "stop": 1608992178921}