{"name": "test_invalid_auth[data0]", "status": "passed", "steps": [{"name": "Выполняем проверку авторизации с не валидными данными", "status": "passed", "start": 1608744784392, "stop": 1608744785525}], "parameters": [{"name": "data", "value": "{'username': 'zZRuX2bkedEGrAY@yandex.ru', 'password': 'M6gUqbDHx5fVgZ6MV@yandex.ru'}"}], "start": 1608744784392, "stop": 1608744785525, "uuid": "7e0cf23f-aeaf-4ced-89ad-635ab4ac7850", "historyId": "3f1318d08e4a3fb9919def63d79e8d71", "testCaseId": "e7a886291d134bf95574e708e5eab128", "fullName": "tests.test_api.test_login.TestApiAuth#test_invalid_auth", "labels": [{"name": "tag", "value": "flaky(reruns=3, reruns_delay=2)"}, {"name": "tag", "value": "api"}, {"name": "parentSuite", "value": "tests.test_api"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestApiAuth"}, {"name": "host", "value": "LAPTOP-VDKHCJMI"}, {"name": "thread", "value": "16544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api.test_login"}]}